# **Homework 2**

## **Basis of Numpy Library**

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these **arrays**.

To use Numpy, we first need to import the `numpy` package:

In [1]:
# import library
import numpy as np

### **Arrays**

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

- The number of dimensions is the rank of the array;

- The shape of an array is a tuple of integers giving the size of the array along each dimension.

**Exercise:**
- What is an **array**?
- Give an example that can be represented by an array.

In [14]:
# create 1d array
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


In [16]:
# print shape
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.shape)

(5,)


In [15]:
# create 2d array
import numpy as np
array_2d =np.array([[1, 2, 3],[4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [1]:
# print shape
import numpy as np
array_2d =np.array([[1, 2, 3],[4, 5, 6]])
print(array_2d.shape)

(2, 3)


In [2]:
# create 3d array
import numpy as np
array_3d =np.array([[[1, 2, 3],[4, 5, 6]],[[11,12,13],[14,15,16]]])
print(array_3d)
print (array_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
3


In [15]:
# print shape
import numpy as np
array_3d =np.array([[[1, 2, 3],[4, 5, 6]],[[11,12,13],[14,15,16]]])
print(array_3d.shape)
print(array_3d.ndim)

(2, 2, 3)
3


### **Array Indexing**

In [5]:
# print the second element in your 1d array
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d[1])

2


In [3]:
# print the first row second element in your 2d array
import numpy as np
array_2d =np.array([[1, 2, 3],[4, 5, 6]])
print(array_2d[0,1])

2


In [13]:
# print the first rank first row second element in your 3d array
import numpy as np
array_3d =np.array([[[1, 2, 3],[4, 5, 6]],[[11,12,13],[14,15,16]]])
print(array_3d[0,0,1])

2


### **Array Operations**

In [18]:
# create 2 2d-array
import numpy as np
arr1=np.full((3,3),2,dtype=int)
arr2=np.full((3,3),2,dtype=int)
# Elementwise sum; both produce an array
print(arr1+arr2)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [12]:
# Elementwise difference; both produce an array
import numpy as np
array_2d_A=np.array(range(5))
array_2d_B=np.array(range(4))
# Elementwise sum; both produce an array
result=np.array(array_2d_A*array_2d_B)
print(array_2d_A.shape)
print(array_2d_B.shape)
print(result)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
# Elementwise division; both produce an array


In [ ]:
# Elementwise product; both produce the array


In [ ]:
# Dot product or matrix multiplication


## Basis of OpenCV

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
# read file
import cv2
from google.colab.patches import cv2_imshow

filename = '/content/drive/MyDrive/PhD/DLBOI/HW2/hw2.png' # your file path


In [ ]:
# Rotate


In [ ]:
# Denoise by filter
